### ISSUE TITLE
Docs: Incomplete Docker image name

### ISSUE THREAD

**Issue by golles** [EverythingSmartHome/everything-presence-addons#20]
First of all thank you for sharing configs to run in docker, for people without addons!

The examples here are using the wrong image name.
https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html#advanced-alternative-install-with-docker-no-supervisor

`everything-presence-mmwave-configurator` should be `everythingsmarthome/everything-presence-mmwave-configurator`

```
docker run -d -e HA_URL=http://HA_URL:8123 -e HA_TOKEN=LONG_LIVE_TOKEN -p 8099:8099 --name everything-presence-mmwave-configurator everythingsmarthome/everything-presence-mmwave-configurator:latest 
```

```yaml
services:
  zones:
    ports:
      - 8099:8099
    image: everythingsmarthome/everything-presence-mmwave-configurator:latest
    container_name: everything-presence-mmwave-configurator
    environment:
      - HA_URL=http://10.0.1.11:8123
      - HA_TOKEN=123-generate-token-at-url:8123/profile/security-456
```

I've only tested the compose one, so please double check the `docker run` command
