### ISSUE TITLE
Unable to get addon to run as standalone docker container

### ISSUE THREAD

**Issue by jcrowegitHu8** [EverythingSmartHome/everything-presence-addons#54]
I want this to run as a standalone docker container so I can try and add some feature to the UI myself.  So any help to get this running would be appreciated.

Core 2025.3.2
Supervisor 2025.03.2
Operating System 14.2
Frontend 20250306.0

I copied the docker-compose template from official documentation and modified it.
https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html

```yaml
# docker-compose.yaml
services:
  zones:
    ports:
      - 8099:8099
    image: everythingsmarthome/everything-presence-mmwave-configurator:1.1.1
    container_name: epl-mmwave-configurator
    environment:
      - HA_URL=http://[Local_IP]:8123
      - HA_TOKEN=[LONG_LIVED_TOKEN]
```

docker container logs
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
curl: (6) Could not resolve host: supervisor
[10:17:46] ERROR: Something went wrong contacting the API
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun backend (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
ERROR:root:Running as a standalone docker container.
 * Serving Flask app 'backend' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
ERROR:root:Exception occurred while connecting to Home Assistant API: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by EverythingSmartHome** [comment]
That should be all you need to do, are you sure the URL and long live token provided are valid?

**Comment by jcrowegitHu8** [comment]
## Progress Update:
I have found 1 part of the issue.  The url has to be SSL.  It appears the api will no work over HTTP.

for others this means in docker-compose.
@EverythingSmartHome   Please update the official documentation as I spent 2 hours figure this out due to copy/paste from the official documentation.  Thank you.

https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html
![Image](https://github.com/user-attachments/assets/a76fc064-c633-4f95-b6c6-d5a2ac1979e2)

```
environment:
      - HA_URL=https://[FQDN or LOCAL_IP]:8123
```

## Next Problem

The next error I'm troubleshooting is.

```
ERROR:root:Exception occurred while connecting to Home Assistant API: HTTPSConnectionPool(host='[FQDN_REMOVED]', port=8123): Max retries exceeded with url: /api/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b68677d1fc0>, 'Connection to [FQDN_REMOVED] timed out. (connect timeout=10)'))
```
Note: for my setup the public FQDN resolve internal to local IP.

I still appreciate any help.  

What I have done so far:
1)I run a curl command directly from the docker host machine and it comes back with success.
```
curl -X GET -H "Authorization: Bearer [SAME_HA_TOKEN_FROM_COMPOSE]" -H "Content-Type: application/json" https://[HA_FQDN]:8123/api/

{"message":"API running."}
```

2)Next step I'll figure out how to get an interactive session with the container to run the curl from there to understand what is different.  It's not working from Portainer directly.  

My thought process right now is that it should be the same result as the host unless there is security at the container level blocking it.

**Comment by EverythingSmartHome** [comment]
There shouldn't be any requirement to use HTTPS as far as I'm aware. So you mean you tried it on http and didn't work, you then went and changed your entire HA setup to use HTTPS, generated a certificate etc and then changed the parameter to Https and it worked?

Or was your HA already using Https?

**Comment by jcrowegitHu8** [comment]
> There shouldn't be any requirement to use HTTPS as far as I'm aware. So you mean you tried it on http and didn't work, you then went and changed your entire HA setup to use HTTPS, generated a certificate etc and then changed the parameter to Https and it worked?
> 
> Or was your HA already using Https?

Correct, my HA was already setup with HTTPS and let's encrypt.  I have had this setup for many years and have done a few clean installs when HA has done some big changes over the years but have always migrated the same DuckDns FQDN and let's encrypt setup to try and stay secure.

Thanks for the clarification.

**Comment by jcrowegitHu8** [comment]
## Progress Update

I figure out the last issue by getting the interactive shell with the container and finding that the FQDN was not resolvable by the container.  I added the extra_hosts to make it resolvable and everything seems to work currently.

For my HomeAssistant setup with DuckDNS and Let's Encrypt  this is the docker-compose.yaml that finally worked for me.

```yaml

services:
  epl-mmwave-configurator:
    ports:
      - 8099:8099
    image: everythingsmarthome/everything-presence-mmwave-configurator:lastest
    container_name: everything-presence-mmwave-configurator
    environment:
      - HA_URL=https://[EXAMPLE].duckdns.org:8123
      - HA_TOKEN=[HA_LONG_LIVED_TOKEN]
    extra_hosts:
        - "[EXAMPLE].duckdns.org:10.X.X.X" #HA_FQDN host and LOCAL IP
```

## Improvement Recommendations.

**To be clear this was all due to my secure setup but I can see a few thing we can improve on for others.**

1)Update the current documentation with a secure example.  Similar to what I put above.
2)Improve the backend.py to check for hostname vs IP have help guide the user though the errors better when it's a stand alone container.  I realize this could be considered over kill but just putting it out there.

### P.S.

1) Thanks again for your responses.
2) How can I reach out to you about creating a temperature sensor module for the EP Lite?  I don't find value in the CO2 modules but really would like temperature.
